"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['liveGBA.py']
DATA_FILES = []
OPTIONS = {'includes':['pyautogui','pygetwindow','signal','logging','sys','schedule','subprocess']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
